## 1. Import all libraries

In [ ]:
import os
import json
import requests
import warnings
import sqlite3
import pandas as pd
from openai import OpenAI
from dotenv import load_dotenv

from urllib3.exceptions import NotOpenSSLWarning
warnings.simplefilter("ignore", NotOpenSSLWarning)

In [120]:
load_dotenv("keys.env")

OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY")
SPOONACULAR_API_KEY = os.environ.get("SPOONACULAR_API_KEY")

## 2. Create cookies and headers
*These variables are used for getting the XHR file from the website*

In [ ]:
cookies = {
    'EDEKA_PRIVACY': '1%40087%7C6%7C5030%40%4091%401759168772089%2C1759168772089%2C1792864772089%40',
    'EDEKA_PRIVACY_CENTER': '',
    'JSESSIONID': '868E369E9FD720B0A453D661690D2FE1',
    'atuserid': '%7B%22name%22%3A%22atuserid%22%2C%22val%22%3A%22OPT-OUT%22%2C%22options%22%3A%7B%22end%22%3A%222026-10-31T18%3A02%3A53.457Z%22%2C%22path%22%3A%22%2F%22%7D%7D',
    'TCPID': '12591202533522197673',
}

headers = {
    'accept': '*/*',
    'accept-language': 'en-US,en;q=0.9,de;q=0.8,vi;q=0.7',
    'if-none-match': '"cvpwz8bzw34oqn"',
    'priority': 'u=1, i',
    'referer': 'https://www.edeka.de/eh/s%C3%BCdwest/edeka-frank-erlachstra%C3%9Fe-45/angebote.jsp',
    'sec-ch-ua': '"Chromium";v="140", "Not=A?Brand";v="24", "Google Chrome";v="140"',
    'sec-ch-ua-mobile': '?0',
    'sec-ch-ua-platform': '"macOS"',
    'sec-fetch-dest': 'empty',
    'sec-fetch-mode': 'cors',
    'sec-fetch-site': 'same-origin',
    'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36',
}

params = {
    'path': 'api/offers?limit=999&marketId=10001604',
}

## 3. Get the data and convert to JSON

In [17]:
response = requests.get('https://www.edeka.de/api/auth-proxy/', params=params, cookies=cookies, headers=headers)
json_data = response.json()
# reduced_items = create_list_from_json(data)

In [ ]:
def create_df_from_json(json_data: json):
	offers = json_data["offers"]

	# --- 2. Normalize the list of offers into a DataFrame ---
	df = pd.json_normalize(offers)

	# --- 3. Keep only the fields you care about ---
	df_selected = df[
		[
			"title",
			"price.value",
			"category.name",
			"descriptions",
			"validTill",
		]
	]

	# Optional: rename columns for clarity
	df_selected = df_selected.rename(columns={
		"price.value": "price",
		"category.name": "category"
	})

	# price as float
	df_selected["price"] = df_selected["price"].astype(float)

	# descriptions is a list; keep the first element if present
	df_selected["descriptions"] = df_selected["descriptions"].str[0]

	# validTill as datetime
	df_selected["validTill"] = pd.to_datetime(df_selected["validTill"], errors="coerce")
	return df_selected

In [60]:
df = create_df_from_json(json_data)

## Simple cleaning

In [61]:
df = df[~df['category'].isin(['Drogerie', 'Tiernahrung', 'Non-Food'])]

In [ ]:
weekday_map = {
    "Montag": 0,
    "Dienstag": 1,
    "Mittwoch": 2,
    "Donnerstag": 3,
    "Freitag": 4,
    "Samstag": 5,
    "Sonntag": 6,
}

def extract_weekday_from_title(title):
    if not isinstance(title, str):
        return None
    
    for name in weekday_map:
        if name in title:
            return weekday_map[name]
    return None

def normalize_df(df: pd.DataFrame) -> pd.DataFrame:
	df = df.copy()

	# Clean raw_title: replace non-breaking space and strip
	df["title"] = (
		df["title"]
		.str.replace("\xa0", " ", regex=False)
		.str.replace(r"[\u2070-\u209F\u00B2\u00B3\u00B9]", "", regex=True)  # remove superscripts
		.str.strip()    
	)

	# Convert price to float
	df["price"] = df["price"].astype(float)

	# Extract target weekday from title
	df["weekday_in_title"] = df["title"].apply(extract_weekday_from_title)

	# Convert validTill to datetime
	df["validTill"] = pd.to_datetime(df["validTill"], errors="coerce")
	current_weekday = df["validTill"].dt.weekday
    
	# Default = Monday (0)
	default_weekday = 0

	weekday_target = df["weekday_in_title"].fillna(default_weekday)

	df["validFrom"] = df["validTill"] - pd.to_timedelta(
		current_weekday - weekday_target, unit="D"
	)
     
	for day_name in weekday_map.keys():
		df["title"] = (
			df["title"]
			.str.replace(f"Ab {day_name} erhältlich: ", "", regex=False)
			.str.replace(f"Am {day_name} erhältlich: ", "", regex=False)
		)
	return df

In [62]:
df = normalize_df(df)

In [ ]:
df = df[~df['descriptions'].str.contains('Topf')]
df = df[~df['descriptions'].str.contains('Deko')]
df = df.sort_values(by=['category', 'title']).reset_index(drop=False)

In [68]:
df.to_csv("offers_clean.csv", index=False, encoding="utf-8")

## 5. Use LLM from OpenAI to generate a JSON with clean item title
*This should be optimized to reduced the LLM runtime*

In [106]:
name_list = df['title'].to_list()
name_list

['Bücklinge Hering',
 'Feinkost Popp Brotaufstrich Alaska-Seelachs',
 'Isländische Seesaiblingsfilets',
 'Schwedenhappen Honig-Senf',
 'Seelachsrückenfilets',
 'Thunfisch-Steaks',
 'Viktoriaseebarschfilets',
 'Alpen Cordon bleu',
 'Bifi Original',
 'Delikatess-Bierschinken',
 'Frische Hähnchenschenkel',
 'Frische Wildschwein-Keule',
 'Frisches Suppenhuhn',
 'Gegrillte Hähnchenkeulen',
 'Herta Finesse',
 'Hofglück Fleischwurst',
 'Hofglück Hähnchen-Frikadellen',
 'Hofglück Lyoner',
 'Hofglück Pfefferbeißer',
 'Hofglück Schweine-Rückenbraten',
 'Hofglück zarte Schweinenackensteaks natur',
 'Hähnchen Unterschenkel',
 'Kirschwasserschinken',
 'Knackige Wiener Würstchen lang',
 'Leberwurst mit Kalbfleisch',
 'Neuburger',
 'Premium-Geflügelwurst-Aufschnitt gemischt',
 'Puten-Rollbraten oder Puten-Ragout',
 'Putenbrust',
 'Reinert Bärchen-Streich',
 'Rindswürstchen',
 'Salami-Aufschnitt extra',
 'Schweinehals',
 'Wasner Münchner Weißwurst',
 'Zart gereiftes Rindfleisch aus Deutschland: Rindersteaks',
 'Zarte Schweinefilets',
 'Zarter Lachsschinken',
 'Afri Cola',
 'Allgäuer Büble Edelbräu',
 'Alnatura Bio Coco-Drink natur',
 'Asbach Uralt',
 'Baden Ortenauer Weinkeller Echt Süß Rosé',
 'Captain Morgan Original Spiced Gold',
 'Chiemseer Hell',
 'Coca-Cola, Mezzo Mix, Fanta Orange',
 'Happy Day',
 'Heineken Lager Bier',
 'Hendrick‘s Gin',
 'Italien: Via al Castello Barolo DOCG',
 'Krombacher Pils',
 'Licor 43',
 'More Zerup',
 'Mumm Sekt',
 'Paulaner Hefe-Weißbier Naturtrüb',
 'Ramazzotti Amaro',
 'Rothaus Tannenzäpfle',
 'Schwarzwald-Sprudel Mineralwasser',
 'Spanien: Bio Alnatura Edition Sauvignon Blanc trocken',
 'Stuttgarter Hofbräu Pilsner',
 'Südafrika: Nederburg Wein',
 'Three Sixty Vodka',
 'Tri Top Sirup',
 'Vitrex Frucht',
 'Württemberg WZG Trollinger mit Lemberger, Trollinger',
 'Württemberg WZG Uhlbacher Weinsteige Trollinger trocken',
 'De Cecco italienische Teigwaren',
 'Dinkelbrötchen',
 'Goldpuder Weizenmehl',
 'Gründerbrot',
 'Kölln Müsli',
 'Nestlé Cerealien',
 'SB-Backstation: Weltmeisterbrötchen',
 'Schlossbrot',
 'Bahlsen Gebäck',
 'Barebells Protein Bar',
 'Chio Tortillas Wild Paprika oder Nacho Cheese',
 'DeBeukelaer Prinzen Rolle Schoko',
 'EDEKA Herzstücke Coconut Heaven',
 'Funnyfrisch Chipsfrisch',
 'Haribo Phantasia oder Color-Rado',
 'Hitschies Fruchtgummis',
 'Kit Kat',
 'Milka Gebäck oder Küchlein',
 'Ricola Original Kräuter ohne Zucker',
 'Ritter Sport Schokolade Bunte Vielfalt',
 'Ritter Sport Tafel vegan Roasted Peanut',
 'XOX Mikrowellen Popcorn',
 'Ab Donnerstag erhältlich; Grana Padano Riserva',
 'Alnatura Bio Barista Hafer Drink mit Soya',
 'Alnatura Bio Bergbauern Gouda gerieben',
 'Alnatura Bio Lassi Mango',
 'Danone Activia',
 'EDEKA Herzstücke High Protein Skyr Natur',
 'Ehrmann Grand Dessert',
 'Fol Epi',
 'Géramont Der Cremige',
 'Kerrygold Käse in Scheiben',
 'Kourellas Griechischer Joghurt',
 'Le Rustique Camembert',
 'Milram Burlander',
 'Miree Frischkäsezubereitung',
 'Patros',
 'Philadelphia Frischkäsezubereitung',
 'Rama',
 'Strähl Raclette',
 'Unsere Heimat – echt & gut Allgäuer Hofkäse',
 'Unsere Heimat – echt & gut Bioland-Allgäuer Bergkäse',
 'Unsere Heimat – echt & gut Frische Milch',
 'Weideglück Landjoghurt',
 'Weihenstephan Butter',
 'Adventsgesteck',
 'Avocados',
 'Blumenkohl',
 'EDEKA Bio Möhren',
 'EDEKA Bio Rispentomaten',
 'EDEKA Herzstücke Granatapfelkerne',
 'EDEKA Herzstücke Papayas',
 'EDEKA Herzstücke Raclette Kartoffeln',
 'Elstar Äpfel',
 'Gut & Günstig Gurken',
 'Gut & Günstig Orangen',
 'Handbundmix',
 'Heidelbeeren',
 'Nordmann Adventskranz',
 'Rosenstrauß',
 'Suppengrün',
 'Unsere Heimat –  echt & gut Wirsing',
 'Unsere Heimat – echt & gut Birnen Xenia',
 'Unsere Heimat – echt & gut Feldsalat',
 'Unsere Heimat – echt & gut Hokkaido Kürbis',
 'Alnatura Bio Apfelessig naturtrüb',
 'Alnatura Bio Kichererbsenwaffeln',
 'Alnatura Bio Schoko Reis Waffeln Vollmilch',
 'Bahlsen Comtess Kuchen',
 'Bonne Maman Erdnuss Creme',
 'EDEKA Bio Chiasamen',
 'EDEKA Herzstücke feinster Zucker',
 'Henglein Kartoffel-Gnocchi',
 'Knack & Back Croissants',
 'Knorr Feinschmecker Saucen oder Suppen',
 'Knorr Salat Krönung',
 'Landliebe Aufstriche',
 'Mandel-Streifen',
 'Melitta Barista Caffè Crema',
 'Melitta Kaffee',
 'Meßmer Wohfühltee',
 'Namdong Chicken Jjigae, Beef Jjigae',
 'Nesquik Original Nachfüllbeutel',
 'Olea Salbo natives Olivenöl extra',
 'Oma‘s Apfelschnitten',
 'Papa Joe’s Original Mayonnaise',
 'Rapso 100% reines Rapsöl',
 'SB-Backstation: Pizza Margherita',
 'Seeberger Erdbeeren gefriergetrocknet',
 'Simmler Konfitüre',
 'Sonnen Bassermann Hühnernudeleintopf',
 'Spreewaldhof Gewürzgurken Spreelinge',
 'Starbucks Kapseln',
 'Tchibo Caffè Crema oder Espresso',
 'Vegan Billie Green Salami Baguette-Style',
 'Ben & Jerry’s',
 'Dr. Oetker Pizza Ristorante',
 'Frosta Fisch',
 'Iglo Spinat',
 'Langnese Cremissimo']

In [88]:
OpenAI.api_ley = OPENAI_API_KEY
client = OpenAI()

In [112]:
import json
from openai import OpenAI

client = OpenAI()  

def extract_ingredients_batch(names, batch_size=30, model="gpt-4.1-mini"):
    """
    names: list of German product names (strings)
    returns: list of dicts [{ "original": ..., "ingredient_en": ... }, ...]
    """
    all_records = []

    for start in range(0, len(names), batch_size):
        batch = names[start:start + batch_size]

        prompt = f"""
You are a supermarket product normalizer.

Given a list of German supermarket product names, extract the core ingredient
or product type in English.

Rules:
- Remove brand names (e.g. "Hofglück", "Edeka").
- Ignore quantity, packaging, promotional text ("Aktion", "XXL", etc.).
- Keep each result short and generic (e.g. "pork back roast", "cola soft drink").
- If you are unsure, give your best guess.

Return a JSON array with this exact shape and nothing else:

[
  {{"original": "<original German name>", "ingredient_en": "<english core ingredient>"}},
  ...
]

Here is the list of product names as JSON:

{json.dumps(batch, ensure_ascii=False)}
"""

        response = client.responses.create(
            model=model,
            input=prompt,
            max_output_tokens=1024,
        )

        # Get raw text from the model
        text = response.output_text.strip()

        # Try to isolate the JSON array (in case the model adds extra text)
        start_idx = text.find("[")
        end_idx = text.rfind("]")

        if start_idx == -1 or end_idx == -1:
            raise ValueError(
                f"Model response for batch starting at index {start} "
                f"does not contain a JSON array:\n{text}"
            )

        json_str = text[start_idx:end_idx + 1]

        try:
            records = json.loads(json_str)
        except json.JSONDecodeError as e:
            raise ValueError(
                f"Failed to parse JSON for batch starting at index {start}: {e}\n"
                f"Raw response:\n{text}"
            )

        all_records.extend(records)

    return all_records

In [114]:
records = extract_ingredients_batch(name_list, batch_size=30)

In [115]:
map_df = pd.DataFrame(records)  # columns: original, ingredient_en

df = df.merge(
    map_df,
    left_on="title",
    right_on="original",
    how="left"
).drop(columns=["original"])

In [ ]:
import pandas as pd

def add_ingredient_column(df, col_name="title", batch_size=50):
    all_records = []
    titles = df[col_name].tolist()

    for i in range(0, len(titles), batch_size):
        batch = titles[i : i + batch_size]
        records = extract_ingredients_batch(batch)  # function from above
        all_records.extend(records)

    # Convert to DataFrame and merge back on the original title
    df_map = pd.DataFrame(all_records)  # columns: original, ingredient_en
    df_with_ingredient = df.merge(
        df_map,
        left_on=col_name,
        right_on="original",
        how="left"
    ).drop(columns=["original"])

    return df_with_ingredient

df = add_ingredient_column(df, col_name="title")

In [117]:
df.tail()

,index,title,price,category,descriptions,validTill,weekday_in_title,validFrom,ingredient_en
160,160,Ben & Jerry’s,4.44,Tiefkühl,"tiefgefroren, versch. Sorten, 465 ml, (1 L = 9...",2025-11-22,NaN,2025-11-17,ice cream
161,161,Dr. Oetker Pizza Ristorante,1.99,Tiefkühl,"oder Bistro Flammkuchen, versch. Sorten, tiefg...",2025-11-22,NaN,2025-11-17,frozen pizza
162,162,Frosta Fisch,2.79,Tiefkühl,"tiefgefroren, versch. Sorten, 240-450 g, (1 kg...",2025-11-22,NaN,2025-11-17,fish
163,163,Iglo Spinat,1.79,Tiefkühl,"tiefgefroren, versch. Sorten, 500–750 g, (1 kg...",2025-11-22,NaN,2025-11-17,spinach
164,164,Langnese Cremissimo,3.99,Tiefkühl,"tiefgefroren, versch. Sorten, 825–900 ml, (1 L...",2025-11-22,NaN,2025-11-17,ice cream

In [122]:
df.to_csv("translated.csv", index=False, encoding="utf-8")

In [138]:
import json
from openai import OpenAI

client = OpenAI()  # assumes OPENAI_API_KEY in env


def classify_ingredients_batch(ingredients, batch_size=20, model="gpt-4.1-mini"):
    """
    Classify ingredients with:
      - can_cook: True/False
      - diet_type: 'vegan' | 'vegetarian' | 'normal'
      - use_cooking: True/False
      - use_baking: True/False
      - use_drinks: True/False

    ingredients: list of English ingredient names (strings)
    returns: list of dicts
    """
    all_records = []

    for start in range(0, len(ingredients), batch_size):
        batch = ingredients[start:start + batch_size]

        system_prompt = """
You are helping classify food ingredients for recipes.

For each English ingredient name, decide:

1) can_cook (boolean):
   - true  = can realistically be used in cooking, baking, OR drink recipes
            (examples: pork, rice, carrots, onions, red wine, white wine, beer,
                       stock, cocoa powder, sugar, lemon juice)
   - false = not typically used as an ingredient in recipes
            (examples: cola soft drink, energy drink, cleaning products,
                       non-food items, packaging-only items)

2) diet_type (string):
   - "vegan"       = contains no animal products (no meat, fish, dairy, eggs, honey, gelatin, etc.)
   - "vegetarian"  = may contain dairy, eggs, or honey, but NO meat, fish, or seafood.
   - "normal"      = contains meat, fish, seafood, gelatin, or other non-vegetarian ingredients,
                     OR unclear/mixed (when in doubt, choose "normal").

3) use_cooking (boolean):
   - true  = commonly used in savory / general cooking (stir-fries, stews, sauces, roasts, etc.).
   - false = not normally used in cooking.

4) use_baking (boolean):
   - true  = commonly used in baking or desserts (cakes, cookies, breads, pastries, sweets).
   - false = rarely used in baking.

5) use_drinks (boolean):
   - true  = commonly used in drinks (cocktails, smoothies, teas, coffees, punches, etc.).
            Includes many alcohols (wine, rum, vodka, liqueurs) and juices.
   - false = not usually used directly in drink recipes.

A single ingredient can have multiple true flags, e.g.:
- "egg"      -> use_cooking = true, use_baking = true, use_drinks = false
- "milk"     -> use_cooking = true, use_baking = true, use_drinks = true
- "red wine" -> use_cooking = true, use_baking = maybe true, use_drinks = true

If you are not sure about a usage category, set it to false.
"""

        user_prompt = f"""
Classify each of these ingredient names.

OUTPUT FORMAT (IMPORTANT):

- Output ONE valid JSON object PER LINE (JSONL format).
- Do NOT wrap them in an array.
- Do NOT add commas between lines.
- Do NOT add any explanations or extra text.

Each line must be a JSON object with this shape:

{{
  "ingredient_en": "<ingredient name>",
  "can_cook": true or false,
  "diet_type": "vegan" or "vegetarian" or "normal",
  "use_cooking": true or false,
  "use_baking": true or false,
  "use_drinks": true or false
}}

Here is the list of ingredient names as a JSON array:

{json.dumps(batch, ensure_ascii=False)}
"""

        response = client.responses.create(
            model=model,
            input=[
                {"role": "system", "content": system_prompt},
                {"role": "user",  "content": user_prompt},
            ],
            max_output_tokens=800,
        )

        # Concatenate all text chunks
        chunks = []
        for out in response.output:
            for part in out.content:
                # depending on SDK, .text may already be a string; adjust if needed
                chunks.append(part.text)
        raw_text = "".join(chunks)

        # Parse JSONL line-by-line
        for line in raw_text.splitlines():
            line = line.strip()
            if not line:
                continue

            try:
                obj = json.loads(line)
            except json.JSONDecodeError:
                # most likely a truncated last line; you can log it if you like
                # print("Skipping unparsable line:", line)
                continue

            # Basic sanity check
            if "ingredient_en" not in obj:
                continue

            all_records.append(obj)

    return all_records

In [139]:

unique_ingredients = sorted(df["ingredient_en"].dropna().unique().tolist())

classified = classify_ingredients_batch(unique_ingredients)

class_df = pd.DataFrame(classified)
# columns: ingredient_en, can_cook, diet_type, use_cooking, use_baking, use_drinks

df = df.merge(class_df, on="ingredient_en", how="left")

In [141]:
df.to_csv('new_columns.csv', index=False, encoding="utf-8")

## 6. Connect a recipe API (Spoonacular) to query some recipes

In [145]:
df_can_cook = df[df['can_cook'] == True]

In [144]:
normal_cooking = df_can_cook[(df_can_cook['diet_type'] == 'normal') & (df_can_cook['use_cooking'] == True)]

In [147]:
normal_cooking.head(36)

,index,title,price,category,descriptions,validTill,weekday_in_title,validFrom,ingredient_en,can_cook,diet_type,use_cooking,use_baking,use_drinks
0,0,Bücklinge Hering,1.11,Fisch & Meeresfrüchte,"ausgenommen und geräuchert, 100 g",2025-11-22,NaN,2025-11-17,smoked herring,True,normal,True,False,False
1,1,Feinkost Popp Brotaufstrich Alaska-Seelachs,0.99,Fisch & Meeresfrüchte,"150 g, (1 kg = 6,60)",2025-11-22,NaN,2025-11-17,pollock spread,True,normal,True,False,False
2,2,Isländische Seesaiblingsfilets,3.29,Fisch & Meeresfrüchte,"mit Haut, 100 g",2025-11-22,NaN,2025-11-17,arctic char fillets,True,normal,True,False,False
5,5,Thunfisch-Steaks,3.99,Fisch & Meeresfrüchte,"das beste Stück vom Thunfisch, ideal zum Grill...",2025-11-22,3.0,2025-11-20,tuna steaks,True,normal,True,False,False
6,6,Viktoriaseebarschfilets,1.99,Fisch & Meeresfrüchte,"aus Binnenfischerei, zartes, rosa Fleisch, 100 g",2025-11-22,NaN,2025-11-17,Nile perch fillets,True,normal,True,False,False
7,7,Alpen Cordon bleu,1.49,Fleisch & Wurst,"vom Schwein, mit Bergkäse und Rinderrohschinke...",2025-11-22,NaN,2025-11-17,cordon bleu,True,normal,True,False,False
9,9,Delikatess-Bierschinken,1.29,Fleisch & Wurst,"DLG-prämiert, gluten-/laktosefrei, auch in Sel...",2025-11-22,NaN,2025-11-17,beer ham,True,normal,True,False,False
10,10,Frische Hähnchenschenkel,4.99,Fleisch & Wurst,"auf Wunsch auch gewürzt, mit Rückenstück, HKL ...",2025-11-22,5.0,2025-11-22,fresh chicken thighs,True,normal,True,False,False
11,11,Frische Wildschwein-Keule,2.99,Fleisch & Wurst,"ohne Knochen, 100 g",2025-11-22,3.0,2025-11-20,fresh wild boar leg,True,normal,True,False,False
12,12,Frisches Suppenhuhn,7.99,Fleisch & Wurst,"ohne Innereien, HKL A, SB-verpackt, Haltungsfo...",2025-11-22,NaN,2025-11-17,fresh soup chicken,True,normal,True,False,False
14,14,Herta Finesse,1.49,Fleisch & Wurst,"versch. Sorten, 100 g, (1 kg = 14,90)",2025-11-22,NaN,2025-11-17,pork sausage,True,normal,True,False,False
16,16,Hofglück Hähnchen-Frikadellen,1.49,Fleisch & Wurst,"in der Gusspfanne gebraten, kalt und warm ein ...",2025-11-22,NaN,2025-11-17,chicken meat patties,True,normal,True,False,False
17,17,Hofglück Lyoner,1.29,Fleisch & Wurst,"versch. Sorten, 100 g, (1 kg = 12,90)",2025-11-22,NaN,2025-11-17,lyoner sausage,True,normal,True,False,False
18,18,Hofglück Pfefferbeißer,4.49,Fleisch & Wurst,"geräuchert, 200 g, (1 kg = 22,45)",2025-11-22,NaN,2025-11-17,pepper sausage,True,normal,True,False,False
19,19,Hofglück Schweine-Rückenbraten,9.99,Fleisch & Wurst,"vollfleischig, edeka.de/air-fryer, 1 kg",2025-11-22,NaN,2025-11-17,pork back roast,True,normal,True,False,False
20,20,Hofglück zarte Schweinenackensteaks natur,8.49,Fleisch & Wurst,"SB-verpackt, 3 Stück, 450 g, (1 kg = 18,87)",2025-11-22,NaN,2025-11-17,pork neck steaks,True,normal,True,False,False
21,21,Hähnchen Unterschenkel,9.99,Fleisch & Wurst,"SB-verpackt, ca. 500 g, Haltungsform 2, 1 kg",2025-11-22,NaN,2025-11-17,chicken drumsticks,True,normal,True,False,False
22,22,Kirschwasserschinken,1.69,Fleisch & Wurst,"gegart, Haltungsform 2, 100 g",2025-11-22,NaN,2025-11-17,kirschwasser ham,True,normal,True,False,False
23,23,Knackige Wiener Würstchen lang,1.29,Fleisch & Wurst,"Spitzenqualität im zarten Natursaitling, glute...",2025-11-22,NaN,2025-11-17,vienna sausages,True,normal,True,False,False
24,24,Leberwurst mit Kalbfleisch,1.49,Fleisch & Wurst,verfeinert mit laktosefreier Sahne und einer l...,2025-11-22,NaN,2025-11-17,liver sausage with veal,True,normal,True,False,False
25,25,Neuburger,1.99,Fleisch & Wurst,"ofengebackener Fleischkäse, ein Brotzeitschman...",2025-11-22,NaN,2025-11-17,pork sausage,True,normal,True,False,False
26,26,Premium-Geflügelwurst-Aufschnitt gemischt,1.29,Fleisch & Wurst,"4-fach sortiert, aus 100% Geflügelfleisch, glu...",2025-11-22,NaN,2025-11-17,mixed poultry cold cuts,True,normal,True,False,False
27,27,Puten-Rollbraten oder Puten-Ragout,9.99,Fleisch & Wurst,"aus der saftigen Oberkeule, mit einer feinen I...",2025-11-22,NaN,2025-11-17,turkey roast or stew,True,normal,True,False,False
28,28,Putenbrust,2.29,Fleisch & Wurst,"in Geflügelbouillon schonend gegart, anschließ...",2025-11-22,NaN,2025-11-17,turkey breast,True,normal,True,False,False
29,29,Reinert Bärchen-Streich,1.49,Fleisch & Wurst,"125 g, (1 kg = 11,92)",2025-11-22,NaN,2025-11-17,spreadable sausage,True,normal,True,False,False
30,30,Rindswürstchen,1.29,Fleisch & Wurst,"geräuchert, herzhaft-knackig, gluten-/laktosef...",2025-11-22,NaN,2025-11-17,beef sausage,True,normal,True,False,False
32,32,Schweinehals,8.99,Fleisch & Wurst,"ohne Knochen, ein saftiges Bratenstück, Haltun...",2025-11-22,NaN,2025-11-17,pork neck,True,normal,True,False,False
33,33,Wasner Münchner Weißwurst,3.49,Fleisch & Wurst,"300 g, (1 kg = 11,63)",2025-11-22,NaN,2025-11-17,white sausage,True,normal,True,False,False
34,34,Zart gereiftes Rindfleisch aus Deutschland: Ri...,2.99,Fleisch & Wurst,"aus der Hüfte geschnitten, ideal für Grill und...",2025-11-22,NaN,2025-11-17,beef steak,True,normal,True,False,False
35,35,Zarte Schweinefilets,1.69,Fleisch & Wurst,"im Gemüse-Brätmantel, Haltungsform 2, 100 g",2025-11-22,NaN,2025-11-17,pork fillet,True,normal,True,False,False
43,43,Chiemseer Hell,14.99,Getränke,"20 x 0,5 L, zzgl. 3,10 Pfand, (1 L = 1,50)",2025-11-22,NaN,2025-11-17,lager beer,True,normal,True,False,True
46,46,Heineken Lager Bier,4.99,Getränke,"auch 0,0% Alkoholfrei, 6 x 0,33 L, zzgl. 0,48 ...",2025-11-22,NaN,2025-11-17,lager beer,True,normal,True,False,True
141,141,Landliebe Aufstriche,1.49,Sonstiges,"versch. Sorten, 180–200 g, (1 kg = 8,28-7,45)",2025-11-22,NaN,2025-11-17,spreads,True,normal,True,False,False
146,146,"Namdong Chicken Jjigae, Beef Jjigae",1.49,Sonstiges,"und weitere Sorten, 83–120 g, (1 kg = 17,95-12...",2025-11-22,NaN,2025-11-17,jjigae stew,True,normal,True,False,False
161,161,Dr. Oetker Pizza Ristorante,1.99,Tiefkühl,"oder Bistro Flammkuchen, versch. Sorten, tiefg...",2025-11-22,NaN,2025-11-17,frozen pizza,True,normal,True,False,False
162,162,Frosta Fisch,2.79,Tiefkühl,"tiefgefroren, versch. Sorten, 240-450 g, (1 kg...",2025-11-22,NaN,2025-11-17,fish,True,normal,True,False,False

In [ ]:
params = {
    "ingredients": ",".join(ingredients[:10]),  # limit to a handful
    "number": 10,
    "apiKey": SPOONACULAR_API_KEY,
}
headers = {
    'Content-Type': 'application/json',
}
resp = requests.get("https://api.spoonacular.com/recipes/findByIngredients", params=params, headers=headers)
recipes = resp.json()

In [ ]:
y =json.dumps(recipes)
print(y)